### PR TITLE
Merge master

### PR DESCRIPTION
**Pull request by pranavkm**

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@pranavkm__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft Open Technologies, Inc. and real humans are currently evaluating your PR.</p>

TTYL, MSOTBOT;

**Comment by pranavkm** [comment]
Merge xunit/master into dev. We pull some of their packages when building and seems like they've moved things around which is breaking the CI. Seemed like a good opportunity to merge their master branch.

**Comment by pranavkm** [comment]
cc @bricelam

**Comment by pranavkm** [comment]
We'll pull this in post beta4.

**Comment by bricelam** [comment]
Will also need to...
- Ensure the right dependencies are defined
- Ensure our fork's nupkgs don't collide with any of the official ones
- Update [aspnet/aspnet.xunit](https://github.com/aspnet/aspnet.xunit)
- React to any breaking changes in all of our repo's tests

**Pull request closed without merging**
